# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - reportingsystem

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://reportingcomplaints.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6c682351ab4142f3a757909442a9b727 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_209826de6d544d1c8e9ee3ea106eebdb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: reportingcomplaints.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6c682351ab4142f3a757909442a9b727 }}/reporting:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'reportingsystem'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f42531ec66e74213b407e78e30bd8cf3 }}
        images: 'reportingcomplaints.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6c682351ab4142f3a757909442a9b727 }}/reporting:${{ github.sha }}'